# Generated by Django 4.2.1 on 2023-06-26 16:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='User UUID')),
                ('email_address', models.EmailField(max_length=255, unique=True, verbose_name='Email Address')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Account Active?')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Account Admin?')),
                ('is_profile', models.BooleanField(default=False, verbose_name='Account Profile?')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Account Verified?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('verification_token', models.CharField(blank=True, max_length=200, null=True, verbose_name='Verfication Token')),
                ('reset_password_token', models.CharField(blank=True, max_length=200, null=True, verbose_name='Reset Password Token')),
                ('reset_instance_token', models.CharField(blank=True, max_length=200, null=True, verbose_name='Reset Instance Token')),
                ('password_reset_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
